[package]
name = "kosmos-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kosmos-renderer = { path = "../kosmos-renderer"}
kosmos-pipeline = { path = "../kosmos-pipeline"}
